export const ADD_PASSWORD = "ADD_PASSWORD";
export const FETCH_PASSWORD = "FETCH_PASSWORD";
export const EDIT_PASSWORD = "EDIT_PASSWORD";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const DELETE_PASSWORD = "DELETE_PASSWORD";
